import React, { useRef } from 'react';
import Head from 'next/head'
import { transparentize } from 'polished'
import styled from "styled-components"
import Input from '../components/Input'
import TextSelect from '../components/TextSelect'
import TextArea from '../components/TextArea'
import emailjs, { init } from '@emailjs/browser';

export default function Contato(props: any) {
    init("R_QGa4kXL-kPLt7hQ");
    const form: any = useRef();
    
    const sendEmail = (e: any) => {
        e.preventDefault();

        emailjs.sendForm('service_uwxl6td', 'template_19jnuuo', String(form.current), 'R_QGa4kXL-kPLt7hQ')
            .then((result) => {
                console.log(result.text);
            }, (error) => {
                console.log(error.text);
            });
    };

    const optionsState = [
        { value: 'SC', label: 'Santa Catarina' },
        { value: 'PR', label: 'Paraná' },
        { value: 'RS', label: 'Rio Grande do Sul' },
    ];

    const optionsInterest = [
        { value: 'Conhecendo', label: 'Estou apenas conhecendo' },
        { value: 'Estudando', label: 'Estou estudando para um projeto' },
        { value: 'Orcamento', label: 'Já conheço e quero fazer um orçamento' },
        { value: 'Sem interesse', label: 'Não tenho interesse' },
        { value: 'Comprar agora', label: 'Quero comprar agora' },
    ];

    return (
        <Wrapper>
            <Head>
                <title>Green Gold Ambiental - Contato</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Content>
                <Title>Faça seu orçamento!</Title>
                <InputWrapper ref={form} onSubmit={sendEmail}>
                    <Input
                        type={"text"}
                        name={"name"}
                        placeholder={"Digite seu nome completo"}
                        text={"Nome"}
                    />
                    <Input
                        type={"email"}
                        name={"email"}
                        placeholder={"Digite seu e-mail"}
                        text={"Email"}
                    />
                    <Input
                        type={"text"}
                        name={"company"}
                        placeholder={"Digite o nome da sua empresa"}
                        text={"Empresa"}
                    />
                    <Input
                        type={"text"}
                        name={"phone"}
                        placeholder={"(YY) XXXXX-XXXX"}
                        text={"Telefone"}
                    />
                    <TextSelect
                        options={optionsState}
                        name={"state"}
                        text={"Estado"}
                    />
                    <TextSelect
                        options={optionsInterest}
                        name={"interest"}
                        text={"Qual o seu interesse?"}
                    />
                    <Input
                        type={"text"}
                        name={"profession"}
                        placeholder={"Digite sua profissão"}
                        text={"Qual a sua profissão"}
                    />
                    <Input
                        type={"text"}
                        name={"area"}
                        placeholder={"Digite o tamanho da área em metros"}
                        text={"Tamanho da área para hidrossemeadura (m2)"}
                    />
                    <TextArea
                        name={"message"}
                        text={"Quer falar conosco? Mande uma mensagem!"}
                        placeholder='Digite sua mensagem...'
                    />
                    <Button>Enviar informações</Button>
                </InputWrapper>
            </Content>

        </Wrapper>
    )
}

const Wrapper = styled.main`
  
`

const Title = styled.h1`
    margin-bottom: 76px;
    font-weight: 600;
    font-size: 36px;
    line-height: 42px;
    color: ${p => p.theme.attentionForeground};
`

const Content = styled.div`
    min-height: 100vh;

    margin-top: 192px;

    display: flex;
    flex-direction: column;
    align-items: center;
`

const InputWrapper = styled.form`
    width: 770px;
    height: 1628px;
    padding-top: 80px;
    margin-bottom: 150px;
    background-color: ${p => transparentize(0.2 , p.theme.primaryBackground)};

    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 42px;
`
const Button = styled.button`
    padding: 28px 68px;
    background-color: ${p => p.theme.attentionForeground};
    color: ${p => p.theme.primaryForeground};
    font-weight: 500;
    font-size: 22px;
    box-shadow: 0 0 0 0;
    border: 0 none;
    outline: 0;
    margin-top: 40px;
`