import Head from 'next/head'
import { transparentize } from 'polished'
import styled from "styled-components"
import Input from '../components/Input'
import Select from '../components/Select'
import TextArea from '../components/TextArea'

export default function Contato(props: any) {

    


    return (
        <Wrapper>
            <Head>
                <title>Green Gold Ambiental - Contato</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Content>
                <Title>Faça seu orçamento!</Title>
                <InputWrapper>
                    <Input text={"Nome"}>Digite seu nome completo</Input>
                    <Input text={"Email"}>Digite seu e-mail</Input>
                    <Input text={"Empresa"}>Digite o nome da sua empresa</Input>
                    <Input type={"phone"} text={"Telefone"}>(YY) XXXXX-XXXX</Input>
                    <Select text={"Estado"}>
                        <option value="" disabled selected>Escolha seu estado</option>
                        <option>Santa Catarina</option>
                        <option>Paraná</option>
                        <option>Rio Grande do Sul</option>
                    </Select>
                    <Select text={"Qual o seu interesse?"}>
                        <option value="" disabled selected>Escolha seu interesse</option>
                        <option>Estou apenas conhecendo</option>
                        <option>Estou estudando para um projeto</option>
                        <option>Já conheço e quero fazer um orçamento</option>
                        <option>Não tenho interesse</option>
                        <option>Quero comprar agora</option>
                    </Select>
                    <Input text={"Qual a sua profissão"}>Digite sua profissão</Input>
                    <Input text={"Tamanho da área para hidrossemeadura (m2)"}>Digite o tamanha da área em metros</Input>
                    <TextArea text={"Quer falar conosco? Mande uma mensagem!"} placeholder='Digite sua mensagem...'></TextArea>
                    <Button>Enviar informações</Button>
                </InputWrapper>
            </Content>

        </Wrapper>
    )
}

const Wrapper = styled.main`
  
`

const Title = styled.h1`
    margin-bottom: 76px;
    font-weight: 600;
    font-size: 36px;
    line-height: 42px;
    color: ${p => p.theme.attentionForeground};
`

const Content = styled.div`
    min-height: 100vh;

    margin-top: 192px;

    display: flex;
    flex-direction: column;
    align-items: center;
`

const InputWrapper = styled.div`
    width: 770px;
    height: 1628px;
    padding-top: 80px;
    margin-bottom: 150px;
    background-color: ${p => transparentize(0.2 , p.theme.primaryBackground)};

    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 42px;
`
const Button = styled.button`
    padding: 28px 68px;
    background-color: ${p => p.theme.attentionForeground};
    color: ${p => p.theme.primaryForeground};
    font-weight: 500;
    font-size: 22px;
    box-shadow: 0 0 0 0;
    border: 0 none;
    outline: 0;
    margin-top: 40px;
`