import Head from 'next/head'
import styled from "styled-components"
import AskBox from "../components/AskBox"

export default function duvidas(props: any) {
    return (
        <Wrapper>
            <Head>
                <title>Green Gold Ambiental - Dúvidas</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Content>
                <Title>Dúvidas frequentes</Title>
                <AskBox
                    hiddenText={"A hidrossemeadura da GREEN GOLD fica verde na aplicação.A vegetação leva em média 90 dias para se desenvolver.Esse tempo pode variar um poucopara MAIS ou para MENOS dependendode chuvas, solos e espécies usadas."}
                >
                    Quanto tempo demora para ficar verde/fechar?
                </AskBox>
                <AskBox
                    hiddenText={"Sim damos garantia de 1 ano para nossos serviços; Caso não cresça a vegetação no prazo de 60 dias pra hidromanta e 90 dias para hidrossemeaduras, a GREEN GOLD irá agendar replante de garantia ou reforço."}
                >
                    Tem GARANTIA? E se não nascer?
                </AskBox>
                <AskBox
                    hiddenText={"Isso não é comum pois usamos colas para evitar isso. Mas caso ocorra, a garantia cobre e voltamos para refazer."}
                >
                    E se chover muito e escorrer?
                </AskBox>
                <AskBox
                    hiddenText={"Não. Nosso material dispensa qualquer tipo de preparo de solo em taludes. Só usa este tipo de preparo de solo empresas que usam mulches de papel picado ou outros resíduos."}
                >
                    Precisa abrir covinhas no talude? Picoteamento?
                </AskBox>
                <AskBox
                    hiddenText={"Nós da GREEN GOLD utilizamos um mix de sementes com no mínimo 4 espécies diferentes. Estas plantas têm crescimento rápido e são plantas bem rústicas, se adaptando aos mais diversos tipos de solo e clima."}
                >
                    Que tipo de semente que se usa?
                </AskBox>
                <AskBox
                    hiddenText={"Nosso mix padrão tem algumas plantas que podem chegar a 1 metro de altura (Brizantha). Caso seja necessário podemos eliminar esta espécie e as outras chegam até cerca de 40-50 cm (Ruziziensis)."}
                >
                    Cresce muito o capim? Que altura que fica?
                </AskBox>
                <AskBox
                    hiddenText={"Não. Grama esmeralda não tem sementes vendidas em escala comercial. Além disso sementes tem dormência e demoram muito germinar. Placas são feitas com mudas."}
                >
                    Tem como fazer Hidrossemeadura de grama esmeralda?
                </AskBox>
                <AskBox
                    hiddenText={"30-50 cm com o mix de sementes padrão. O capim-vetiver pode chegar a 5 metros, mas não pode ser aplicado por hidrossemeadura pois não tem sementes. Seu plantio somente é feito por mudas."}
                >
                    A raiz vai muito fundo no solo?
                </AskBox>
                <AskBox
                    hiddenText={"Não se pode dizer isso. A vegetação vai proteger a superfície do solo e evitar erosões superficiais. A estabilidade do talude depende da inclinação do corte, drenagem, tipo de solo. Mas com certeza com vegetação é melhor do que sem. E quanto mais passar o tempo mais estabilidade a vegetação vai proporcionar devido ao enraizamento"}
                >
                    Depois de fazer a Hidrossemeadura não cai mais o talude?
                </AskBox>
                <AskBox
                    hiddenText={"Vai demorar um pouco mais para fechar. Regiões que tem época de seca (tipo 6 meses sem chuva) não fazemos hidrossemeadura nessa época. O Sul e Sudeste do Brasil não apresentam época de seca assim, por isso trabalhamos o ano todo sem problemas."}
                >
                    E se não chover?
                </AskBox>
                <AskBox
                    hiddenText={"Não. Utilizamos um corante orgânico alimentício sem nenhum risco ao Meio Ambiente. O mulch perde a cor dentro de uma semana pois se degrada com a luz do sol."}
                >
                    O Corante utilizado na Hidrossemeadura não é tóxico <br /> ao Meio Ambiente?
                </AskBox>
            </Content>

        </Wrapper>
    )
}

const Wrapper = styled.main`
  
`

const Title = styled.h1`
    margin-bottom: 76px;
    font-weight: 600;
    font-size: 36px;
    line-height: 42px;
    color: ${p => p.theme.attentionForeground};
`

const Content = styled.div`
    min-height: 100vh;

    margin: 232px 0 0 205px;

    display: flex;
    flex-direction: column;

    background - image: url('/images/banner2.svg');
    background - size: cover;

`