import Head from 'next/head'
import Link from 'next/link'
import styled from 'styled-components'
import QuemUsa from '../public/images/QuemUsa.image'
import Beneficios from '../views/Beneficios'
import Landing from '../views/Landing.view'
import OQueE from '../views/OQueE.view'
import QueTipo from '../views/QueTipo.view'


export default function Home(props: any) {

  return (
    <Wrapper>
      <Head>
        <title>Green Gold Ambiental</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Landing />
      <OQueE />
      <Beneficios />
      <QueTipo />

    </Wrapper>
  )
}

const Wrapper = styled.main`
  
`


