import Head from 'next/head'
import Link from 'next/link'
import styled from 'styled-components'
import Landing from '../view/Landing.view'
import OQueE from '../view/OQueE.view'


export default function Home(props: any) {

  return (
    <Wrapper>
      <Head>
        <title>Green Gold Ambiental</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Landing />
      <OQueE />
      

    </Wrapper>
  )
}

const Wrapper = styled.main`
  
`


