import Head from 'next/head'
import styled from 'styled-components'
import InfoContent from '../components/InfoContent'
import Locals from '../public/images/Locals.image'

export default function Locais(props: any) {

    return (
        <Wrapper>
                    
            <Head>
                <title>Green Gold Ambiental - Locais</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <InfoContent
                backgroundColor="default"
                height={100}
                leftStyle={Left}
                left={
                    <WrapperLeft>
                        <Title>Locais de atuação</Title>
                        <Paragraph>A Green Gold Ambiental atua em toda a <br /> região sul do Brasil, que inclui os <br /> estados de <strong>Santa Catarina, Rio Grande <br /> do Sul</strong> e <strong>Paraná.</strong></Paragraph>
                    </WrapperLeft>
                }
                rightStyle={Right}
                right={
                    <>
                        <Locals />
                    </>
                }>
            </InfoContent>
        </Wrapper>



    )
}

const Wrapper = styled.main`
    margin-top: 216px;
`

const Content = styled.div`
    display: grid;
    grid-template-columns: 1fr 1fr;
    height: 100%;
`

const Left = styled.div`
    display: flex;
    flex-direction: column;
    align-items: flex-end;
`

const WrapperLeft = styled.div`
    align-self: flex-end;
    z-index:1;
    margin-right: 70px;

    strong {
        color: #EA1818;
    }

`

const Title = styled.h1`
    font-weight: 600;
    font-size: 36px;
    line-height: 42px;
    color: ${p => p.theme.attentionForeground};
    margin-bottom: 36px;
`

const Paragraph = styled.span`
    width: 470px;
    font-weight: 500;
    font-size: 24px;
    line-height: 28px;
`

const Right = styled.div`
    margin-top: -100px;
    /* margin-left: -70px; */
`

